/**
 * @fileoverview gRPC-Web generated client stub for helloworld
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.21.6
// source: proto/helloworld.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_helloworld_pb from '../proto/helloworld_pb';


export class GreeterClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSayHello = new grpcWeb.MethodDescriptor(
    '/helloworld.Greeter/SayHello',
    grpcWeb.MethodType.UNARY,
    proto_helloworld_pb.HelloRequest,
    proto_helloworld_pb.HelloReply,
    (request: proto_helloworld_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    proto_helloworld_pb.HelloReply.deserializeBinary
  );

  sayHello(
    request: proto_helloworld_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null): Promise<proto_helloworld_pb.HelloReply>;

  sayHello(
    request: proto_helloworld_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_helloworld_pb.HelloReply) => void): grpcWeb.ClientReadableStream<proto_helloworld_pb.HelloReply>;

  sayHello(
    request: proto_helloworld_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_helloworld_pb.HelloReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/helloworld.Greeter/SayHello',
        request,
        metadata || {},
        this.methodDescriptorSayHello,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/helloworld.Greeter/SayHello',
    request,
    metadata || {},
    this.methodDescriptorSayHello);
  }

  methodDescriptorSayRepeatHello = new grpcWeb.MethodDescriptor(
    '/helloworld.Greeter/SayRepeatHello',
    grpcWeb.MethodType.SERVER_STREAMING,
    proto_helloworld_pb.RepeatHelloRequest,
    proto_helloworld_pb.HelloReply,
    (request: proto_helloworld_pb.RepeatHelloRequest) => {
      return request.serializeBinary();
    },
    proto_helloworld_pb.HelloReply.deserializeBinary
  );

  sayRepeatHello(
    request: proto_helloworld_pb.RepeatHelloRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<proto_helloworld_pb.HelloReply> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/helloworld.Greeter/SayRepeatHello',
      request,
      metadata || {},
      this.methodDescriptorSayRepeatHello);
  }

}

